#pragma once
#include <any>
#include <string>
#include <map>
#include <guiddef.h>
#include <vector>
#include <xlocale>
#include <sstream>
#include <algorithm>
#include <iostream>
#include <fstream>
#include <sstream>
#include <unordered_map>